/*
 * Exstream Orchestration
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.util.UUID;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for FlowModelSnapshotFilter
 */
public class FlowModelSnapshotFilterTest {
    private final FlowModelSnapshotFilter model = new FlowModelSnapshotFilter();

    /**
     * Model tests for FlowModelSnapshotFilter
     */
    @Test
    public void testFlowModelSnapshotFilter() {
        // TODO: test FlowModelSnapshotFilter
    }

    /**
     * Test the property 'domain'
     */
    @Test
    public void domainTest() {
        // TODO: test domain
    }

    /**
     * Test the property 'ids'
     */
    @Test
    public void idsTest() {
        // TODO: test ids
    }

    /**
     * Test the property 'dasIds'
     */
    @Test
    public void dasIdsTest() {
        // TODO: test dasIds
    }

    /**
     * Test the property 'dasVersions'
     */
    @Test
    public void dasVersionsTest() {
        // TODO: test dasVersions
    }

    /**
     * Test the property 'searchString'
     */
    @Test
    public void searchStringTest() {
        // TODO: test searchString
    }

    /**
     * Test the property 'caseSensitive'
     */
    @Test
    public void caseSensitiveTest() {
        // TODO: test caseSensitive
    }

    /**
     * Test the property 'wholeWord'
     */
    @Test
    public void wholeWordTest() {
        // TODO: test wholeWord
    }

    /**
     * Test the property 'published'
     */
    @Test
    public void publishedTest() {
        // TODO: test published
    }

    /**
     * Test the property 'publishedBy'
     */
    @Test
    public void publishedByTest() {
        // TODO: test publishedBy
    }

    /**
     * Test the property 'publishDateStart'
     */
    @Test
    public void publishDateStartTest() {
        // TODO: test publishDateStart
    }

    /**
     * Test the property 'publishDateEnd'
     */
    @Test
    public void publishDateEndTest() {
        // TODO: test publishDateEnd
    }

    /**
     * Test the property 'unpublishDateStart'
     */
    @Test
    public void unpublishDateStartTest() {
        // TODO: test unpublishDateStart
    }

    /**
     * Test the property 'unpublishDateEnd'
     */
    @Test
    public void unpublishDateEndTest() {
        // TODO: test unpublishDateEnd
    }

    /**
     * Test the property 'effectiveDate'
     */
    @Test
    public void effectiveDateTest() {
        // TODO: test effectiveDate
    }

}
