/*
 * Exstream Orchestration
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.openapitools.client.model.FlowStep;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for FlowStepFlow
 */
public class FlowStepFlowTest {
    private final FlowStepFlow model = new FlowStepFlow();

    /**
     * Model tests for FlowStepFlow
     */
    @Test
    public void testFlowStepFlow() {
        // TODO: test FlowStepFlow
    }

    /**
     * Test the property 'inputChannel'
     */
    @Test
    public void inputChannelTest() {
        // TODO: test inputChannel
    }

    /**
     * Test the property 'flowSteps'
     */
    @Test
    public void flowStepsTest() {
        // TODO: test flowSteps
    }

}
