/*
 * Exstream Orchestration
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.openapitools.client.model.PluginWizardStep;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for PluginWizardConfig
 */
public class PluginWizardConfigTest {
    private final PluginWizardConfig model = new PluginWizardConfig();

    /**
     * Model tests for PluginWizardConfig
     */
    @Test
    public void testPluginWizardConfig() {
        // TODO: test PluginWizardConfig
    }

    /**
     * Test the property 'outcomeMappingSupported'
     */
    @Test
    public void outcomeMappingSupportedTest() {
        // TODO: test outcomeMappingSupported
    }

    /**
     * Test the property 'assuredDeliverySupported'
     */
    @Test
    public void assuredDeliverySupportedTest() {
        // TODO: test assuredDeliverySupported
    }

    /**
     * Test the property 'outcomeMappingRequired'
     */
    @Test
    public void outcomeMappingRequiredTest() {
        // TODO: test outcomeMappingRequired
    }

    /**
     * Test the property 'analyticsSupported'
     */
    @Test
    public void analyticsSupportedTest() {
        // TODO: test analyticsSupported
    }

    /**
     * Test the property 'additionalFilesInputHandlingSupported'
     */
    @Test
    public void additionalFilesInputHandlingSupportedTest() {
        // TODO: test additionalFilesInputHandlingSupported
    }

    /**
     * Test the property 'additionalFilesInputHandlingOnly'
     */
    @Test
    public void additionalFilesInputHandlingOnlyTest() {
        // TODO: test additionalFilesInputHandlingOnly
    }

    /**
     * Test the property 'restrictedUseDefault'
     */
    @Test
    public void restrictedUseDefaultTest() {
        // TODO: test restrictedUseDefault
    }

    /**
     * Test the property 'validators'
     */
    @Test
    public void validatorsTest() {
        // TODO: test validators
    }

    /**
     * Test the property 'secureChannelHostVerificationRequired'
     */
    @Test
    public void secureChannelHostVerificationRequiredTest() {
        // TODO: test secureChannelHostVerificationRequired
    }

    /**
     * Test the property 'authenticationProvided'
     */
    @Test
    public void authenticationProvidedTest() {
        // TODO: test authenticationProvided
    }

    /**
     * Test the property 'jobExpirationSupported'
     */
    @Test
    public void jobExpirationSupportedTest() {
        // TODO: test jobExpirationSupported
    }

    /**
     * Test the property 'steps'
     */
    @Test
    public void stepsTest() {
        // TODO: test steps
    }

}
