/*
 * Exstream Orchestration
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for PublicOrcConfiguration
 */
public class PublicOrcConfigurationTest {
    private final PublicOrcConfiguration model = new PublicOrcConfiguration();

    /**
     * Model tests for PublicOrcConfiguration
     */
    @Test
    public void testPublicOrcConfiguration() {
        // TODO: test PublicOrcConfiguration
    }

    /**
     * Test the property 'assuredDeliveryEnabled'
     */
    @Test
    public void assuredDeliveryEnabledTest() {
        // TODO: test assuredDeliveryEnabled
    }

    /**
     * Test the property 'flowScriptDebuggingEnabled'
     */
    @Test
    public void flowScriptDebuggingEnabledTest() {
        // TODO: test flowScriptDebuggingEnabled
    }

    /**
     * Test the property 'baseSubscription'
     */
    @Test
    public void baseSubscriptionTest() {
        // TODO: test baseSubscription
    }

    /**
     * Test the property 'subscriptionEnabled'
     */
    @Test
    public void subscriptionEnabledTest() {
        // TODO: test subscriptionEnabled
    }

}
