/*
 * Exstream Orchestration
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for SecretInfo
 */
public class SecretInfoTest {
    private final SecretInfo model = new SecretInfo();

    /**
     * Model tests for SecretInfo
     */
    @Test
    public void testSecretInfo() {
        // TODO: test SecretInfo
    }

    /**
     * Test the property 'b64Content'
     */
    @Test
    public void b64ContentTest() {
        // TODO: test b64Content
    }

    /**
     * Test the property 'decodedContent'
     */
    @Test
    public void decodedContentTest() {
        // TODO: test decodedContent
    }

}
