/*
 * Exstream Design
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.HashMap;
import java.util.LinkedHashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;
import org.openapitools.client.model.DataSource;
import org.openapitools.client.model.ExportPackageMetadata;
import org.openapitools.client.model.ImportConflictResource;
import org.openapitools.client.model.ImportFoundCategory;
import org.openapitools.client.model.ImportFoundResource;
import org.openapitools.client.model.ReplacementPolicySettings;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for ImportResponse
 */
public class ImportResponseTest {
    private final ImportResponse model = new ImportResponse();

    /**
     * Model tests for ImportResponse
     */
    @Test
    public void testImportResponse() {
        // TODO: test ImportResponse
    }

    /**
     * Test the property 'metadata'
     */
    @Test
    public void metadataTest() {
        // TODO: test metadata
    }

    /**
     * Test the property 'exportPackageUUID'
     */
    @Test
    public void exportPackageUUIDTest() {
        // TODO: test exportPackageUUID
    }

    /**
     * Test the property 'policies'
     */
    @Test
    public void policiesTest() {
        // TODO: test policies
    }

    /**
     * Test the property 'importedResources'
     */
    @Test
    public void importedResourcesTest() {
        // TODO: test importedResources
    }

    /**
     * Test the property 'ignoredResources'
     */
    @Test
    public void ignoredResourcesTest() {
        // TODO: test ignoredResources
    }

    /**
     * Test the property 'conflictedResources'
     */
    @Test
    public void conflictedResourcesTest() {
        // TODO: test conflictedResources
    }

    /**
     * Test the property 'existingResources'
     */
    @Test
    public void existingResourcesTest() {
        // TODO: test existingResources
    }

    /**
     * Test the property 'importedCategories'
     */
    @Test
    public void importedCategoriesTest() {
        // TODO: test importedCategories
    }

    /**
     * Test the property 'ignoredCategories'
     */
    @Test
    public void ignoredCategoriesTest() {
        // TODO: test ignoredCategories
    }

    /**
     * Test the property 'deploymentPackages'
     */
    @Test
    public void deploymentPackagesTest() {
        // TODO: test deploymentPackages
    }

    /**
     * Test the property 'deletedResources'
     */
    @Test
    public void deletedResourcesTest() {
        // TODO: test deletedResources
    }

    /**
     * Test the property 'placeholderDataSources'
     */
    @Test
    public void placeholderDataSourcesTest() {
        // TODO: test placeholderDataSources
    }

    /**
     * Test the property 'resourcePermissions'
     */
    @Test
    public void resourcePermissionsTest() {
        // TODO: test resourcePermissions
    }

    /**
     * Test the property 'warnings'
     */
    @Test
    public void warningsTest() {
        // TODO: test warnings
    }

    /**
     * Test the property 'schemaMetadata'
     */
    @Test
    public void schemaMetadataTest() {
        // TODO: test schemaMetadata
    }

}
