/*
 * Exstream Design
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import java.util.UUID;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for ImportConflictResource
 */
public class ImportConflictResourceTest {
    private final ImportConflictResource model = new ImportConflictResource();

    /**
     * Model tests for ImportConflictResource
     */
    @Test
    public void testImportConflictResource() {
        // TODO: test ImportConflictResource
    }

    /**
     * Test the property 'type'
     */
    @Test
    public void typeTest() {
        // TODO: test type
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'version'
     */
    @Test
    public void versionTest() {
        // TODO: test version
    }

    /**
     * Test the property 'state'
     */
    @Test
    public void stateTest() {
        // TODO: test state
    }

    /**
     * Test the property 'newName'
     */
    @Test
    public void newNameTest() {
        // TODO: test newName
    }

    /**
     * Test the property 'origId'
     */
    @Test
    public void origIdTest() {
        // TODO: test origId
    }

    /**
     * Test the property 'userSelectedAction'
     */
    @Test
    public void userSelectedActionTest() {
        // TODO: test userSelectedAction
    }

    /**
     * Test the property 'performedAction'
     */
    @Test
    public void performedActionTest() {
        // TODO: test performedAction
    }

    /**
     * Test the property 'locked'
     */
    @Test
    public void lockedTest() {
        // TODO: test locked
    }

    /**
     * Test the property 'lockedBy'
     */
    @Test
    public void lockedByTest() {
        // TODO: test lockedBy
    }

}
