/*
 * Exstream Design
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for Output
 */
public class OutputTest {
    private final Output model = new Output();

    /**
     * Model tests for Output
     */
    @Test
    public void testOutput() {
        // TODO: test Output
    }

    /**
     * Test the property 'category'
     */
    @Test
    public void categoryTest() {
        // TODO: test category
    }

    /**
     * Test the property 'driver'
     */
    @Test
    public void driverTest() {
        // TODO: test driver
    }

    /**
     * Test the property 'prodFile'
     */
    @Test
    public void prodFileTest() {
        // TODO: test prodFile
    }

    /**
     * Test the property 'appLevel'
     */
    @Test
    public void appLevelTest() {
        // TODO: test appLevel
    }

}
