/*
 * Exstream Design
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import java.util.UUID;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for ResourceMetadata
 */
public class ResourceMetadataTest {
    private final ResourceMetadata model = new ResourceMetadata();

    /**
     * Model tests for ResourceMetadata
     */
    @Test
    public void testResourceMetadata() {
        // TODO: test ResourceMetadata
    }

    /**
     * Test the property 'subtype'
     */
    @Test
    public void subtypeTest() {
        // TODO: test subtype
    }

    /**
     * Test the property 'variableType'
     */
    @Test
    public void variableTypeTest() {
        // TODO: test variableType
    }

    /**
     * Test the property 'variableIsArray'
     */
    @Test
    public void variableIsArrayTest() {
        // TODO: test variableIsArray
    }

    /**
     * Test the property 'resourceTemplate'
     */
    @Test
    public void resourceTemplateTest() {
        // TODO: test resourceTemplate
    }

    /**
     * Test the property 'originalSource'
     */
    @Test
    public void originalSourceTest() {
        // TODO: test originalSource
    }

    /**
     * Test the property 'displayName'
     */
    @Test
    public void displayNameTest() {
        // TODO: test displayName
    }

    /**
     * Test the property 'dialogueVersion'
     */
    @Test
    public void dialogueVersionTest() {
        // TODO: test dialogueVersion
    }

    /**
     * Test the property 'dialogueSerialization'
     */
    @Test
    public void dialogueSerializationTest() {
        // TODO: test dialogueSerialization
    }

    /**
     * Test the property 'dialogueEncoding'
     */
    @Test
    public void dialogueEncodingTest() {
        // TODO: test dialogueEncoding
    }

    /**
     * Test the property 'hasContentAuthorFrames'
     */
    @Test
    public void hasContentAuthorFramesTest() {
        // TODO: test hasContentAuthorFrames
    }

    /**
     * Test the property 'defaultSampleFileId'
     */
    @Test
    public void defaultSampleFileIdTest() {
        // TODO: test defaultSampleFileId
    }

    /**
     * Test the property 'usesDesignPack'
     */
    @Test
    public void usesDesignPackTest() {
        // TODO: test usesDesignPack
    }

    /**
     * Test the property 'dataSourceEligible'
     */
    @Test
    public void dataSourceEligibleTest() {
        // TODO: test dataSourceEligible
    }

    /**
     * Test the property 'selectionVariable'
     */
    @Test
    public void selectionVariableTest() {
        // TODO: test selectionVariable
    }

    /**
     * Test the property 'userFriendlyName'
     */
    @Test
    public void userFriendlyNameTest() {
        // TODO: test userFriendlyName
    }

}
