/*
 * Exstream Design
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import java.util.HashMap;
import java.util.Map;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for Rule
 */
public class RuleTest {
    private final Rule model = new Rule();

    /**
     * Model tests for Rule
     */
    @Test
    public void testRule() {
        // TODO: test Rule
    }

    /**
     * Test the property 'mRefUsageRule'
     */
    @Test
    public void mRefUsageRuleTest() {
        // TODO: test mRefUsageRule
    }

    /**
     * Test the property 'rule'
     */
    @Test
    public void ruleTest() {
        // TODO: test rule
    }

}
