/*
 * Exstream Rationalization
 * **For internal use of the product only**
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.util.UUID;
import org.openapitools.client.model.FragmentRefRequest;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for FragmentRequest
 */
public class FragmentRequestTest {
    private final FragmentRequest model = new FragmentRequest();

    /**
     * Model tests for FragmentRequest
     */
    @Test
    public void testFragmentRequest() {
        // TODO: test FragmentRequest
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'description'
     */
    @Test
    public void descriptionTest() {
        // TODO: test description
    }

    /**
     * Test the property 'isIncluded'
     */
    @Test
    public void isIncludedTest() {
        // TODO: test isIncluded
    }

    /**
     * Test the property 'dasId'
     */
    @Test
    public void dasIdTest() {
        // TODO: test dasId
    }

    /**
     * Test the property 'fragTolerance'
     */
    @Test
    public void fragToleranceTest() {
        // TODO: test fragTolerance
    }

    /**
     * Test the property 'fragOccurrences'
     */
    @Test
    public void fragOccurrencesTest() {
        // TODO: test fragOccurrences
    }

    /**
     * Test the property 'type'
     */
    @Test
    public void typeTest() {
        // TODO: test type
    }

    /**
     * Test the property 'isLibraryRule'
     */
    @Test
    public void isLibraryRuleTest() {
        // TODO: test isLibraryRule
    }

}
