/*
 * Exstream Orchestration
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.util.UUID;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import org.openapitools.client.JSON;

/**
 * FlowInstanceCountsFilter
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-03-17T13:55:50.549398439Z[Europe/Lisbon]")
public class FlowInstanceCountsFilter {
  public static final String SERIALIZED_NAME_FLOW_MODEL_IDS = "flowModelIds";
  @SerializedName(SERIALIZED_NAME_FLOW_MODEL_IDS)
  private List<UUID> flowModelIds;

  public static final String SERIALIZED_NAME_START_DATE_START = "startDateStart";
  @SerializedName(SERIALIZED_NAME_START_DATE_START)
  private OffsetDateTime startDateStart;

  public static final String SERIALIZED_NAME_START_DATE_END = "startDateEnd";
  @SerializedName(SERIALIZED_NAME_START_DATE_END)
  private OffsetDateTime startDateEnd;

  public static final String SERIALIZED_NAME_FILL_MISSING_DATA = "fillMissingData";
  @SerializedName(SERIALIZED_NAME_FILL_MISSING_DATA)
  private Boolean fillMissingData;

  public FlowInstanceCountsFilter() {
  }

  public FlowInstanceCountsFilter flowModelIds(List<UUID> flowModelIds) {
    this.flowModelIds = flowModelIds;
    return this;
  }

  public FlowInstanceCountsFilter addFlowModelIdsItem(UUID flowModelIdsItem) {
    if (this.flowModelIds == null) {
      this.flowModelIds = new ArrayList<>();
    }
    this.flowModelIds.add(flowModelIdsItem);
    return this;
  }

   /**
   * Get flowModelIds
   * @return flowModelIds
  **/
  @javax.annotation.Nullable
  public List<UUID> getFlowModelIds() {
    return flowModelIds;
  }

  public void setFlowModelIds(List<UUID> flowModelIds) {
    this.flowModelIds = flowModelIds;
  }


  public FlowInstanceCountsFilter startDateStart(OffsetDateTime startDateStart) {
    this.startDateStart = startDateStart;
    return this;
  }

   /**
   * Get startDateStart
   * @return startDateStart
  **/
  @javax.annotation.Nullable
  public OffsetDateTime getStartDateStart() {
    return startDateStart;
  }

  public void setStartDateStart(OffsetDateTime startDateStart) {
    this.startDateStart = startDateStart;
  }


  public FlowInstanceCountsFilter startDateEnd(OffsetDateTime startDateEnd) {
    this.startDateEnd = startDateEnd;
    return this;
  }

   /**
   * Get startDateEnd
   * @return startDateEnd
  **/
  @javax.annotation.Nullable
  public OffsetDateTime getStartDateEnd() {
    return startDateEnd;
  }

  public void setStartDateEnd(OffsetDateTime startDateEnd) {
    this.startDateEnd = startDateEnd;
  }


  public FlowInstanceCountsFilter fillMissingData(Boolean fillMissingData) {
    this.fillMissingData = fillMissingData;
    return this;
  }

   /**
   * Get fillMissingData
   * @return fillMissingData
  **/
  @javax.annotation.Nullable
  public Boolean getFillMissingData() {
    return fillMissingData;
  }

  public void setFillMissingData(Boolean fillMissingData) {
    this.fillMissingData = fillMissingData;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    FlowInstanceCountsFilter flowInstanceCountsFilter = (FlowInstanceCountsFilter) o;
    return Objects.equals(this.flowModelIds, flowInstanceCountsFilter.flowModelIds) &&
        Objects.equals(this.startDateStart, flowInstanceCountsFilter.startDateStart) &&
        Objects.equals(this.startDateEnd, flowInstanceCountsFilter.startDateEnd) &&
        Objects.equals(this.fillMissingData, flowInstanceCountsFilter.fillMissingData);
  }

  @Override
  public int hashCode() {
    return Objects.hash(flowModelIds, startDateStart, startDateEnd, fillMissingData);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class FlowInstanceCountsFilter {\n");
    sb.append("    flowModelIds: ").append(toIndentedString(flowModelIds)).append("\n");
    sb.append("    startDateStart: ").append(toIndentedString(startDateStart)).append("\n");
    sb.append("    startDateEnd: ").append(toIndentedString(startDateEnd)).append("\n");
    sb.append("    fillMissingData: ").append(toIndentedString(fillMissingData)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("flowModelIds");
    openapiFields.add("startDateStart");
    openapiFields.add("startDateEnd");
    openapiFields.add("fillMissingData");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

 /**
  * Validates the JSON Element and throws an exception if issues found
  *
  * @param jsonElement JSON Element
  * @throws IOException if the JSON Element is invalid with respect to FlowInstanceCountsFilter
  */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!FlowInstanceCountsFilter.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in FlowInstanceCountsFilter is not found in the empty JSON string", FlowInstanceCountsFilter.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!FlowInstanceCountsFilter.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `FlowInstanceCountsFilter` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      // ensure the optional json data is an array if present
      if (jsonObj.get("flowModelIds") != null && !jsonObj.get("flowModelIds").isJsonNull() && !jsonObj.get("flowModelIds").isJsonArray()) {
        throw new IllegalArgumentException(String.format("Expected the field `flowModelIds` to be an array in the JSON string but got `%s`", jsonObj.get("flowModelIds").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!FlowInstanceCountsFilter.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'FlowInstanceCountsFilter' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<FlowInstanceCountsFilter> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(FlowInstanceCountsFilter.class));

       return (TypeAdapter<T>) new TypeAdapter<FlowInstanceCountsFilter>() {
           @Override
           public void write(JsonWriter out, FlowInstanceCountsFilter value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public FlowInstanceCountsFilter read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of FlowInstanceCountsFilter given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of FlowInstanceCountsFilter
  * @throws IOException if the JSON string is invalid with respect to FlowInstanceCountsFilter
  */
  public static FlowInstanceCountsFilter fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, FlowInstanceCountsFilter.class);
  }

 /**
  * Convert an instance of FlowInstanceCountsFilter to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

