/*
 * Exstream Design
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.api;

import org.openapitools.client.ApiException;
import org.openapitools.client.model.DataResponseRolePermissions;
import org.openapitools.client.model.ListResponseRolePermissions;
import org.openapitools.client.model.RolePermissions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for RolePermissionsControllerApi
 */
@Disabled
public class RolePermissionsControllerApiTest {

    private final RolePermissionsControllerApi api = new RolePermissionsControllerApi();

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void createRole1Test() throws ApiException {
        RolePermissions rolePermissions = null;
        DataResponseRolePermissions response = api.createRole1(rolePermissions);
        // TODO: test validations
    }

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getAllPermissionsTest() throws ApiException {
        String roleName = null;
        ListResponseRolePermissions response = api.getAllPermissions(roleName);
        // TODO: test validations
    }

}
