/*
 * Exstream Design
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.api;

import org.openapitools.client.ApiException;
import org.openapitools.client.model.DataResponseSettingsObj;
import org.openapitools.client.model.GenericResponse;
import org.openapitools.client.model.ListResponseSettingsObj;
import org.openapitools.client.model.SettingsObj;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for SettingsControllerApi
 */
@Disabled
public class SettingsControllerApiTest {

    private final SettingsControllerApi api = new SettingsControllerApi();

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void createMultipleSettingsTest() throws ApiException {
        List<SettingsObj> settingsObj = null;
        ListResponseSettingsObj response = api.createMultipleSettings(settingsObj);
        // TODO: test validations
    }

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void createMultipleSettings1Test() throws ApiException {
        List<SettingsObj> settingsObj = null;
        ListResponseSettingsObj response = api.createMultipleSettings1(settingsObj);
        // TODO: test validations
    }

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void createSettingTest() throws ApiException {
        SettingsObj settingsObj = null;
        DataResponseSettingsObj response = api.createSetting(settingsObj);
        // TODO: test validations
    }

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void createSetting1Test() throws ApiException {
        SettingsObj settingsObj = null;
        DataResponseSettingsObj response = api.createSetting1(settingsObj);
        // TODO: test validations
    }

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void deleteSettingTest() throws ApiException {
        String application = null;
        String name = null;
        GenericResponse response = api.deleteSetting(application, name);
        // TODO: test validations
    }

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getAllSettingsTest() throws ApiException {
        ListResponseSettingsObj response = api.getAllSettings();
        // TODO: test validations
    }

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getSettingTest() throws ApiException {
        String application = null;
        String name = null;
        DataResponseSettingsObj response = api.getSetting(application, name);
        // TODO: test validations
    }

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getSettingsForAppTest() throws ApiException {
        String application = null;
        ListResponseSettingsObj response = api.getSettingsForApp(application);
        // TODO: test validations
    }

}
