/*
 * Exstream Orchestration
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.api;

import org.openapitools.client.ApiException;
import org.openapitools.client.model.DataResponseBoolean;
import org.openapitools.client.model.SecretInfo;
import java.util.UUID;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for SecretControllerApi
 */
@Disabled
public class SecretControllerApiTest {

    private final SecretControllerApi api = new SecretControllerApi();

    /**
     * Migrate secrets to vault.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void migrateVaultTest() throws ApiException {
        Boolean response = api.migrateVault();
        // TODO: test validations
    }

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void rolloverKeysTest() throws ApiException {
        String oldKeyId = null;
        Integer response = api.rolloverKeys(oldKeyId);
        // TODO: test validations
    }

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void secretExistsTest() throws ApiException {
        String domain = null;
        UUID secretId = null;
        DataResponseBoolean response = api.secretExists(domain, secretId);
        // TODO: test validations
    }

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void setSecretTest() throws ApiException {
        String domain = null;
        UUID secretId = null;
        SecretInfo secretInfo = null;
        String response = api.setSecret(domain, secretId, secretInfo);
        // TODO: test validations
    }

}
