/*
 * Exstream Rationalization
 * **For internal use of the product only**
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.api;

import org.openapitools.client.ApiException;
import org.openapitools.client.model.DataResponseTenant;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for ApiV1TenantInternalApi
 */
@Disabled
public class ApiV1TenantInternalApiTest {

    private final ApiV1TenantInternalApi api = new ApiV1TenantInternalApi();

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getTenant1Test() throws ApiException {
        String tenantId = null;
        DataResponseTenant response = api.getTenant1(tenantId);
        // TODO: test validations
    }

}
