/*
 * Exstream Rationalization
 * **For internal use of the product only**
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.api;

import org.openapitools.client.ApiException;
import org.openapitools.client.model.RationalizationResponseObject;
import java.util.UUID;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for MigrationSetReportControllerApi
 */
@Disabled
public class MigrationSetReportControllerApiTest {

    private final MigrationSetReportControllerApi api = new MigrationSetReportControllerApi();

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getMigrationReportDetailsTest() throws ApiException {
        String domain = null;
        UUID id = null;
        RationalizationResponseObject response = api.getMigrationReportDetails(domain, id);
        // TODO: test validations
    }

}
