/*
 * Exstream External Event Puller
 * **For internal use of the product only**
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.api;

import org.openapitools.client.ApiException;
import org.openapitools.client.model.VersionConfig;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for VersionControllerApi
 */
@Disabled
public class VersionControllerApiTest {

    private final VersionControllerApi api = new VersionControllerApi();

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getApiVersionTest() throws ApiException {
        String response = api.getApiVersion();
        // TODO: test validations
    }

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getVersionTest() throws ApiException {
        VersionConfig response = api.getVersion();
        // TODO: test validations
    }

}
